In [7]:
# You are a financial analyst at a top investment firm. Your boss hands you a dataset 
# containing stock prices of 5 companies over a period of 30 days. Your task is to analyze 
# the data and extract meaningful insights! 
# �
# � Task: 
# 1. 
# 2. 
# 3. 
# 4. 
# 5. 
# Create a (30, 5) NumPy array with random stock prices between $100 and $500, 
# where: – – 
# Rows (0-29) represent days (30 days of stock prices). 
# Columns (0-4) represent 5 different companies. 
# Compute the average stock price for each company over the 30-day period. 
# Identify the highest stock price recorded in the dataset and the day and 
# company it belongs to. 
# Normalize the stock prices between 0 and 1 using the formula: 
# [ X_{} =  ] 
# Flag days where any stock drops below $200 as a “⏳ Risky Investment”. 

import numpy as np
dataset=np.random.randint(100,500,(30,5))
Average_stock_prices=np.mean(dataset,axis=0) 
avg=[]
for i in Average_stock_prices:
    avg.append(round(i,1))
print(f"Average stock prices:",avg)
maxi = np.max(dataset)
index = np.argwhere(dataset==maxi)
print(index)
print(f"Highest price recorded: {maxi} at Day {index[0][0]+1}, Company {index[0][1]}")
norm = np.linalg.norm(dataset)
matrix = dataset/norm
print("Normalized Prices : ")
print(matrix)
print("Risky Investments Days:")
for i in range(len(dataset)):
    mask = dataset[i] <200
    if len(dataset[i][mask]) !=0:
        print(f"Day {i+1} : {dataset[i][mask]}")

Average stock prices: [299.7, 301.7, 314.3, 302.3, 317.7]
[[22  3]
 [27  0]]
Highest price recorded: 496 at Day 23, Company 3
Normalized Prices : 
[[0.05407659 0.08979229 0.02590646 0.11444115 0.10387735]
 [0.06690406 0.0251519  0.08149216 0.10563799 0.12399887]
 [0.04074608 0.09104988 0.09960153 0.1084047  0.07721634]
 [0.08677406 0.10085912 0.0304338  0.10915925 0.02565494]
 [0.09155292 0.10890773 0.07847393 0.11519571 0.11670482]
 [0.07922849 0.07973153 0.04954925 0.07973153 0.08300127]
 [0.06589798 0.11569875 0.08048608 0.12324432 0.06111912]
 [0.04326127 0.06262823 0.06438887 0.07595874 0.11268052]
 [0.02741557 0.11469267 0.05231595 0.07117988 0.06715558]
 [0.06287975 0.09054685 0.09960153 0.08274976 0.07067684]
 [0.07998305 0.10387735 0.09482267 0.0450219  0.0555857 ]
 [0.10412887 0.08677406 0.09180444 0.04854317 0.09507419]
 [0.05961001 0.07193444 0.09004381 0.03772785 0.06011304]
 [0.07067684 0.03068532 0.10085912 0.05659178 0.05835241]
 [0.10588951 0.09809242 0.10161368 0.0749

In [9]:
# NASA is preparing a Mars mission ⏳ and needs to efficiently allocate oxygen, water, and 
# food for astronauts over 6 months. Your job as a space engineer is to analyze and optimize 
# resource consumption! 
# �
# � Task: 
# 1. 
# 2. 
# 3. 
# 4. 
# 5. 
# Create a (6, 3) NumPy array, where: – – 
# Rows (0-5) represent months. 
# Columns (0-2) represent oxygen, water, and food consumption (in tons). 
# Compute total resources required for the entire mission. 
# Identify which resource had the highest consumption in any given month and in 
# total. 
# Compute the standard deviation of each resource to measure consistency in 
# consumption. 
# Transpose the matrix to display the resource-wise breakdown by month.


import numpy as np
rand=np.random.randint(1,20,(6,3))
oxygen = np.sum(rand[:, 0])
water= np.sum(rand[:, 1])
food= np.sum(rand[:, 2])
print(f"Total resources needed(tons):Oxygen: {oxygen}, Water: {water}, Food: {food}")
print(f"Highest consumption in a month:")
max_values=np.max(rand,axis=0)
print(max_values)
max_months = np.argmax(rand, axis=0)+1 
print(max_months)
highest_resource_index = np.argmax([oxygen, water, food])
resource_names = ["Oxygen", "Water", "Food"]

print(f"Highest consumption in a month: {resource_names[np.argmax(max_values)]} ({max_values[np.argmax(max_values)]} tons in month {max_months[np.argmax(max_values)]})")
std_oxygen = round(np.std(rand[:, 0]), 1)
std_water = round(np.std(rand[:, 1]), 1)
std_food = round(np.std(rand[:, 2]),1)
print(f"Standard deviation of consumption: Oxygen: {std_oxygen}, Water: {std_water}, Food: {std_food}")
print("Transposed matrix:\n")
print(rand.T)


Total resources needed(tons):Oxygen: 84, Water: 59, Food: 88
Highest consumption in a month:
[19 18 19]
[6 6 1]
Highest consumption in a month: Oxygen (19 tons in month 6)
Standard deviation of consumption: Oxygen: 3.8, Water: 5.4, Food: 5.3
Transposed matrix:

[[14 15  7 12 17 19]
 [ 4 11 12 12  2 18]
 [19  4 17 18 12 18]]


In [13]:
# You are a sports data analyst for an NBA team! You need to analyze the performance of 5 
# players over 10 games to determine their strengths and weaknesses. 
# �
# � Task: 
# 1. 
# 2. 
# 3. 
# 4. 
# 5. 
# Create a (5, 10) NumPy array, where: – – 
# Rows (0-4) represent players. 
# Columns (0-9) represent points scored in 10 games. 
# Compute each player’s average points per game. 
# Identify the best-performing and worst-performing players based on total 
# points. 
# Create a mask to filter out games where a player scored above 30 points 
# (highlighting exceptional performances). 
# Sort players based on their total points in descending order. 

import numpy as np
dataset = np.random.randint(10,50,(5,10))
print(dataset)
avg = (np.sum(dataset,axis =1))/10
avg = [round(a,1) for a in avg]
print("Average points per game:")
print(avg)
sums = np.sum(dataset,axis=1)
print()


[[36 23 41 33 27 24 13 37 14 11]
 [10 43 34 46 20 23 37 20 24 42]
 [30 22 46 18 16 21 27 41 48 46]
 [37 35 43 18 10 33 38 30 11 47]
 [31 35 35 14 20 41 15 45 47 18]]
Average points per game:
[25.9, 29.9, 31.5, 30.2, 30.1]

